import React from "react";





const Legal=()=>{
    return (<div>
        Mentions Légales
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam rhoncus dignissim nisi, a aliquam nisl suscipit consequat. Nunc lobortis dignissim tellus, sed venenatis ex luctus in. Curabitur viverra nec tellus in ultricies. Fusce egestas nisl vel porttitor faucibus. Nunc ac erat ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc sit amet turpis non enim dictum aliquam. Proin ornare, mi non gravida dictum, mi elit rutrum nibh, non aliquet lectus neque non augue.

Donec ultrices neque sit amet laoreet condimentum. Maecenas iaculis viverra nulla eget lobortis. Morbi ultricies justo id odio iaculis condimentum. Donec porttitor turpis quis tincidunt vehicula. Etiam vitae felis in lacus sollicitudin ultricies at eget arcu. Donec nibh augue, consequat nec augue quis, auctor laoreet nisi. Nunc ullamcorper sodales erat, at maximus lorem posuere hendrerit. Praesent condimentum imperdiet dolor, at malesuada massa sollicitudin eu. In dapibus, arcu vel efficitur pharetra, dui diam porttitor mauris, vel tempus risus odio quis orci. Curabitur in semper libero, at faucibus mauris.

Nulla mattis nulla a nunc scelerisque, in feugiat dui laoreet. Morbi nec metus a libero volutpat tincidunt at sed neque. Donec faucibus, arcu non placerat fringilla, erat sapien tempus nulla, sit amet congue urna orci eget lorem. Phasellus vitae egestas odio. Quisque vel mi elit. Quisque cursus turpis tempor mauris maximus cursus. Mauris maximus nunc a ipsum tincidunt, at dapibus nulla faucibus. Quisque sodales nibh volutpat, posuere justo vitae, euismod felis. Cras eget felis massa. Fusce eleifend felis metus, vitae luctus orci cursus quis. Donec sodales, dui ut commodo facilisis, tortor elit ornare turpis, eget ornare metus massa et massa. Donec pulvinar nunc eget justo cursus, vitae fermentum quam lobortis.

Vivamus augue sem, volutpat nec erat in, consectetur luctus ante. Vestibulum lacinia lacus ut ligula ullamcorper, ut pulvinar diam condimentum. Sed feugiat erat vel mollis venenatis. Curabitur aliquam nisl et nibh fringilla hendrerit. Donec ut auctor lacus. Quisque odio elit, aliquet nec elementum eget, aliquam at augue. Proin aliquam, ex a ultricies viverra, lectus metus porttitor libero, et hendrerit risus diam at risus.

Morbi fermentum fringilla porttitor. Etiam ante ipsum, ornare vitae odio nec, rhoncus dictum purus. Aliquam ut ultrices ante. Morbi sollicitudin pulvinar lacus, a interdum purus finibus id. Nulla gravida accumsan sapien, et volutpat mi ultricies porta. Fusce luctus arcu sed sapien ultricies fringilla. Vestibulum et lorem sit amet sapien suscipit porta. Suspendisse leo purus, efficitur non mi nec, rhoncus cursus velit. Pellentesque faucibus non velit in tempus. Quisque pharetra semper pellentesque. Aenean accumsan massa quis est elementum maximus.

Nunc sed felis dui. Nam iaculis magna et tempor consequat. Nulla finibus, eros efficitur porta ullamcorper, nulla diam vehicula ex, at pellentesque leo odio eget tellus. Suspendisse potenti. Nulla auctor turpis id diam tincidunt feugiat. Vestibulum posuere ex massa, quis lobortis mi cursus vel. Pellentesque tincidunt mollis est, luctus laoreet turpis posuere pellentesque. Nunc mollis ullamcorper ipsum sit amet rhoncus. Praesent a neque ac metus maximus sollicitudin in pellentesque arcu.

Duis molestie iaculis accumsan. Donec sem sem, pharetra sed tristique sed, vehicula nec augue. Sed maximus mi a urna aliquam egestas. Phasellus lobortis quam nec justo sagittis, ut lobortis purus eleifend. Ut bibendum erat sit amet iaculis auctor. Duis porttitor risus nibh, a gravida magna suscipit vitae. Donec a mauris sollicitudin, tincidunt purus molestie, finibus quam. Praesent nec mauris eget nisi laoreet luctus. Sed interdum nunc at urna vestibulum vehicula. Quisque quam purus, pulvinar sed sapien commodo, tempor euismod eros.

Etiam velit eros, eleifend malesuada massa quis, iaculis semper purus. Etiam pretium felis et velit consectetur, placerat porta enim accumsan. Morbi faucibus vulputate ligula, non tempus magna dictum in. Sed eget quam convallis, consequat nulla viverra, pretium risus. Phasellus arcu elit, varius in tristique in, faucibus vel erat. Suspendisse odio arcu, consequat vitae pretium eget, suscipit vel quam. In faucibus urna eget ante cursus condimentum. Quisque vel efficitur sapien, id posuere justo. Morbi congue ipsum vel elit volutpat, nec gravida neque ullamcorper. Phasellus pretium vehicula suscipit. Maecenas odio tortor, malesuada eget ex at, pretium euismod est. In hac habitasse platea dictumst. Vestibulum feugiat, metus sit amet egestas scelerisque, elit nibh vulputate diam, eget aliquam ipsum sem a leo. Sed ullamcorper euismod massa, vehicula maximus arcu scelerisque et. Pellentesque efficitur libero cursus, convallis ligula id, malesuada neque.

Suspendisse ligula erat, posuere vitae dignissim aliquet, condimentum vitae risus. Etiam iaculis volutpat ligula a cursus. Sed laoreet massa id justo mollis euismod. Nullam malesuada mattis nibh aliquam vulputate. Morbi nulla est, tempor laoreet ullamcorper et, vestibulum sit amet urna. Nam id ante id erat ultricies bibendum vel vel neque. Quisque ac congue ligula. Aenean quis quam vitae justo aliquet sodales ac a elit. Curabitur ultricies porta magna sed molestie. Ut in placerat neque. Phasellus porta ut magna a ultrices. Nam rhoncus consequat turpis vel dictum. Aliquam ultricies, lectus ac elementum vestibulum, eros lectus molestie odio, id efficitur enim tellus a ipsum. Vivamus mattis sed lacus in ultricies.

Donec egestas urna vitae congue rutrum. Nulla cursus, elit at blandit luctus, sem ante finibus nulla, in pharetra tortor orci ac enim. Suspendisse dignissim euismod augue, ut tempor massa pellentesque in. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent in est rhoncus, facilisis neque eget, rhoncus ipsum. Suspendisse ut orci a sapien tincidunt porttitor. Proin nec ullamcorper leo. Mauris condimentum elit quis dolor lacinia vestibulum. Fusce neque massa, maximus in bibendum ac, maximus sed nisi. Nulla luctus suscipit lectus, vel feugiat dui lobortis ut. Nulla eleifend urna sed arcu tincidunt porta. Nunc quis arcu nisi. Proin quis diam sit amet risus sollicitudin eleifend sit amet ac magna.
    </div>)
}

export default Legal;